apie:
  cms:
    dashboard_template: 'apie/dashboard.html.twig'
  doctrine:
    # build_once: true
    connection_params:
      driver: pdo_sqlite
      path: "%kernel.project_dir%/db.sqlite"
  datalayers:
    #default_datalayer: 'App\Apie\InMemoryDataLayer'
    default_datalayer: 'Apie\DoctrineEntityDatalayer\DoctrineEntityDatalayer'
  bounded_contexts:
    petstore:
      entities_folder: "%kernel.project_dir%/src/Apie/PetStore/Resources/"
      entities_namespace: 'App\Apie\PetStore\Resources'
      actions_folder: "%kernel.project_dir%/src/Apie/PetStore/Actions/"
      actions_namespace: 'App\Apie\PetStore\Actions'
    typesdemo:
      entities_folder: "%kernel.project_dir%/src/Apie/TypesDemo/Resources/"
      entities_namespace: 'App\Apie\TypesDemo\Resources'
      actions_folder: "%kernel.project_dir%/src/Apie/TypesDemo/Actions/"
      actions_namespace: 'App\Apie\TypesDemo\Actions'